# Generated by Django 5.1.2 on 2024-11-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_presentes_reservado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidados',
            name='maximo_acompanhantes',
        ),
    ]
